apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: servicebinding-rds-demo
spec:
  service:
    apiVersion: rds.services.k8s.aws/v1alpha1
    kind: DBInstance
    name: {{ .Values.dbinstance.name }}
  workload:
    selector:
      matchLabels:
        rds-provider: aws
    apiVersion: apps/v1
    kind: Deployment
